### PR TITLE
Beets 465 weather

### PR DESCRIPTION
**Pull request by levertyk**
### Definition of Done:

* [x] Have you checked your [Jira](https://bee-cs458.atlassian.net/jira/software/projects/BEETS/boards/2/backlog) task, to make sure the user acceptance criteria are met?
* [x] Does your code have comments describing its function and reason?

### Source Control

* [x] Is all relevant code checked-in?
* [x] Is this branch ready to be reviewed by the Tech Lead?

### Formatting

* [x] Do your variable names make sense (to others)?
* [x] Have you removed unnecessary Console.logs? 
* [x] Is your code style consistent with other code in the file or the [Style Guide](https://google.github.io/styleguide/jsguide.html)

Screenshot 2023-04-17 at 2 50 54 PM
Screenshot 2023-04-17 at 2 50 33 PM
Screenshot 2023-04-17 at 2 51 10 PM

### CODE REVIEW

**Review by piratecody — CHANGES_REQUESTED** [review]
image

There may be an issue with CSS units and font size here, causing the navbar to scroll. Maybe set a maximum font size?

**Comment by piratecody** [comment]
image

**Comment by levertyk** [comment]
> image

The page will now hide the weather widget when the height is not enough to fit the list elements, and the widget.

**Comment by levertyk** [comment]
Screenshot 2023-04-18 at 12 24 23 PM
Screenshot 2023-04-18 at 12 24 28 PM

**Comment by piratecody** [comment]
image

the contrast on the temperature text here is not ideal. could we make it white?

**Comment by levertyk** [comment]
> image
> 
> the contrast on the temperature text here is not ideal. could we make it white?

The text is now white for the temperature.

**Review by piratecody — APPROVED** [review]

**Pull request merged**
