### PR TITLE
Beets-252 google auth

### PR DESCRIPTION
**Pull request by piratecody**
### Definition of Done:

* [x] Have you checked your [Jira](https://bee-cs458.atlassian.net/jira/software/projects/BEETS/boards/2/backlog) task, to make sure the user acceptance criteria are met?
* [x] Does your code have comments describing its function and reason?

### Tests

* [ ] Do you have Jest tests?
Jest testing doesn't apply to this functionality
* [x] Have you documented your testing criteria and edge cases in your Jira task?

### Source Control

* [x] Is all relevant code checked-in?
* [x] Is this branch ready to be reviewed by the Tech Lead?

### Formatting

* [x] Do your variable names make sense (to others)?
* [x] Have you removed unnecessary Console.logs? 
* [x] Is your code style consistent with other code in the file or the [Style Guide](https://google.github.io/styleguide/jsguide.html)

### CODE REVIEW

**Comment by levertyk** [comment]
Normal Login credentials no longer work.
Screenshot 2023-03-08 at 12 05 37 PM

**Comment by piratecody** [comment]
Close the modal and refresh the page

**Comment by levertyk** [comment]
There are merge conflicts with this branch.

**Review by levertyk — APPROVED** [review]
The code seems to be functioning as intended. All functions of the page remain intact, with the addition of logging in as a google user.

**Pull request merged**
