### PR TITLE
Beets 452

### PR DESCRIPTION
**Pull request by ColbyTief**
### Definition of Done:

* [x] Have you checked your [Jira](https://bee-cs458.atlassian.net/jira/software/projects/BEETS/boards/2/backlog) task, to make sure the user acceptance criteria are met?
* [x] Does your code have comments describing its function and reason?

### Source Control

* [x] Is all relevant code checked-in?
* [x] Is this branch ready to be reviewed by the Tech Lead?

### Formatting

* [x] Do your variable names make sense (to others)?
* [x] Have you removed unnecessary Console.logs? 
* [x] Is your code style consistent with other code in the file or the [Style Guide](https://google.github.io/styleguide/jsguide.html)

### CODE REVIEW

**Comment by ColbyTief** [comment]
No changes to the actual users page, only the modals functionality.
image

**Comment by ColbyTief** [comment]
clicking delete user pulls up this modal
image

**Comment by ColbyTief** [comment]
The main change in this PR is that when the delete button is pressed, both delete and cancel are hidden and the modal remains open until the user closes it.
image

**Comment by ColbyTief** [comment]
the users table then re-renders when the x on the modal is pressed.
image

**Review by levertyk — APPROVED** [review]
Good simple implementation

**Pull request merged**
